listener 1883 0.0.0.0    # TCP port za lokalne i mrežne konekcije
listener 9001            # WebSocket port
protocol websockets      # koristi WS za 9001
allow_anonymous true
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/
